/*
 * shulklink-details.js — per-item + per-section detail fields, merged onto the
 * walkthrough by build-shulklink.js (keyed "sectionId:code").
 *
 * Policy: FACTS are verbatim (area, giver, location, objective, rewards, monster
 * level/location/condition, affinity requirement, gain choices, record names,
 * landmark/location names). STRATEGY / mutex "why" / Nota Bene are concise
 * paraphrases in our own words — ShulkLink's prose is NOT reproduced.
 *
 * Populated section-by-section. Sections without an entry keep their base data.
 */
const G = "Defense Force Soldier", R = "Colony 9 Resident", RF = "Refugee", HT = "Homs Traveller";

module.exports = {
  sections: {
    "4.2": {},
    "4.6": {
      landmarks: ["Tranquil Square", "Anti-Air Battery 3", "Hazzai Cape", "Agora Shore", "Anti-Air Battery 2",
        "Cliff Lake", "Volff Lair", "Viliera Hill", "Sky Stage", "Daksha Shrine", "Observation Platform",
        "Raguel Lake", "Tranquil Grotto", "Raguel Bridge: South", "Raguel Bridge: North", "Windy Cave",
        "Crevasse Waterfall", "Kisk Cave"],
      locations: ["Agora Shore", "Anti-Air Battery 2", "Anti-Air Battery 3", "Hazzai Cape", "Cliff Lake"],
      records: [
        "Equivalent Exchange — first successful trade with an NPC",
        "Lazybones — skip-travel 50 times",
        "Breaking The Ice — party banter on registering a quest for the first time",
        "Idle Chit-Chat — party banter on registering quests 50 times",
        "Ear To The Ground — spoken to people 100 times",
        "Unlucky Sixes — deal exactly 666 damage in one hit",
        "Lucky Sevens — deal exactly 777 damage in one hit",
        "Rear Admiral — perform a back attack 50 times",
        "It Hasn't Lost Its Lustre — open 10 gold chests",
        "Hoarding Treasure — open 50 silver chests",
        "Airing Grievances — defeat 30 flying monsters",
        "Raring To Go — get your first rare ether crystal",
        "Simply Smashing! — smash 100 vision tags",
        "Killer Combo — deal 3,000 damage with a chain attack",
        "Ground To A Pulp — defeat 250 ground-type monsters",
        "Unshakeable Trust — raise two party members to blue affinity",
        "Colony 9 Celebrity — reach 3-star affinity with Colony 9"
      ],
      notaBene: [
        "Around this section you'll likely pick up: Second Wind (10 revivals), Art School (level an art to Lv. 2) and Ninja Skillz (one-shot an enemy with Back Slash).",
        "Item Vision: on collecting an early Bionis' Leg collectable (e.g. Moth Crawler / Sour Gooseberry) a gray vision flags that you'll need several of that item — they're then marked in your inventory until you hit the count.",
        "Arts palette fills up around Lv. 16 (Reyn learns a 9th art) — you can only equip 8, so swap via the Arts submenu."
      ]
    },
    "4.7": {
      landmarks: ["Spiral Valley", "Bask Cave Passage", "Zax Guidepost", "Believer's Paradise"],
      locations: ["Traveller's Rest", "Kasharpa Falls"],
      records: [
        "Explorer — discover the Observation Platform",
        "A generous friend — complete A Young Captain's Rise",
        "Fifty Fine Friends — register your 50th NPC (speak with Jan)",
        "Spider's Web — speak with Zukazu"
      ],
      affinitySteps: [
        "Speak with Dionysus at 12:00 → yellow 'tea friends' (Dionysus/Marcia).",
        "Speak with Marcia at 12:00 → yellow 'interest' (Marcia/Liliana).",
        "Speak with Jolele (Tranquil Square HtH street, right side, night) at 22:00 → blue 'fine grandson' (Jolele/Niranira); registers Jolele.",
        "Speak with Jolele again at 00:00 → green 'grandson's pal' (Jolele/Lukas).",
        "Speak with Betty → green 'big fan' (Betty/Kenny Rohan).",
        "Register Narine by trading (SW of Tranquil Square, day) — don't take her quest yet.",
        "Military District entrance, night — speak with Arnault, answer 'You should ask her yourself' → orange 'together/apart' (Arnault/Françoise).",
        "Speak with Leopold → link with Arnault depends on your Financial Planning route (yellow 'fan' for the frame route / blue 'extreme fan' for the investigate route).",
        "Register Cheryl by trading (Gem Man's Stall NE balcony, overlooking Central Plaza).",
        "Speak with Minnie (sentry at the kids' bridge, 03:00) → orange 'idler/achiever' (Minnie/Monica); registers Minnie.",
        "Speak with Jan (SE wall of the Military District, day) → yellow 'late bloomer?' (Jan/Minnie); registers Jan (trial: Fifty Fine Friends).",
        "Speak with Gorman → yellow 'divorced' (Gorman/Arda).",
        "Speak with Anna at 15:00 → yellow 'mother's friend' (Olga/Anna).",
        "Speak with Olga → yellow 'understanding' (Olga/Ewan).",
        "Speak with Nikita at 11:00 → green 'fine engineer' (Nikita/Satata).",
        "Speak with Zukazu (SW Tranquil Square, night, by a tree) → orange 'hostility' (Zukazu/Marcia); registers Zukazu (trial: Spider's Web).",
        "Register the remaining Colony 9 military: Kantz (north Military District, day), Oleksiy (Gem Man's Stall, night, NE under the building), Meifimeifi (center Military District, night), Nic (enclosed garrison north of Meifimeifi, night) — registering Nic unlocks the trial 'The Brave Protectors'.",
        "Register Perrine (Weapon Dev Lab entrance, sunset).",
        "Speak with Shura (Ether Light, night) → green 'good boss' (Shura/Erik).",
        "Register Peppino (HtH street, night, tree hangout ~4 buildings down).",
        "Register Rosemary (east of the Gem Man's Stall, night) and Werner (Mechon Wreckage Site)."
      ],
      notaBene: [
        "You fight this region's two bosses (Mechon M71, then Mysterious Face on Maguel Road) BEFORE finishing the errata — the boss blocks access to a lot of it, and his defeat doesn't lock anything."
      ]
    },
    "4.8": {
      landmarks: ["Watchpoint Junction", "Supply Road", "Drainage Outlet"],
      locations: ["Splintered Path"]
    },
    "4.9": {
      landmarks: ["Drainage Tunnel", "Drainage Control Room", "Mining Base", "Central Pit: Entrance", "Personnel Lift 2", "Regulation Piston", "Personnel Lift 3", "Freight Elevator", "Glowmoss Lake"],
      locations: ["Test Pit 1", "Test Pit 2", "Test Pit 3", "Test Pit 4", "Storage Depot", "Central Terminal", "Observation Point", "Central Pit: Level 1", "Central Pit: Level 2", "Central Pit: Level 3", "Central Pit: Base Level"],
      records: [
        "Fire It Up — (Dark Kisling fight at the fire ether deposits)",
        "Unbreakable Bond",
        "Chain Gang / Off The Chain — get an extra chain link (vs Xord)",
        "Seasoned Traveller — discover the Freight Elevator (completes the Ether Mine map)"
      ]
    },
    "4.10": {
      landmarks: ["Kelsher Wetlands", "Nopon Merchant Camp", "Crown Tree", "Silent Obelisk", "Glowing Obelisk", "Sororal Statues", "Shining Pond", "Statue Summit"],
      locations: ["Lacus Swamp", "Zaldandia Falls", "Poison Swamp", "Barren Moor", "Dark Swamp", "Igna Territory", "Exile Fortress", "Nopon Refuge", "Oath Sanctuary", "Place of Judgement", "Mauk Floodgate", "Soter Ruins", "Basin Cave", "Altar of Fate"],
      notaBene: [
        "Otharon, Juju and Dickson leave the party at the Sororal Statues — that's when Colony 6 reconstruction opens for business.",
        "Easy 'Cosmic Killer Combo' record here via a lucky multi-link chain attack."
      ]
    }
  },

  items: {
    // ---- 4.2 ----
    "4.2:HTH1": { location: "Outlook Park", gainChoices: "You and Dunban... // Kind of." },

    // ---- 4.6: Colony 9 / Tephra Cave errata ----
    "4.6:Q1":  { giver: G, location: "Tephra Cave Entrance", objective: "Defeat 1 Willow Bunniv in Tephra Cave (near its entrance).", rewards: "1000G", strategy: "Completes your first non-story quest (trial: Problem Solved!)." },
    "4.6:Q3":  { giver: G, location: "Tephra Cave Entrance", objective: "Defeat 2 Singing Brogs (south of the Mag Mell Ruins).", rewards: "1500G" },
    "4.6:Q4":  { giver: G, location: "Tephra Cave Entrance", objective: "Defeat 5 Mell Lizards (hallway between Rear Entrance and Warehouse 2).", rewards: "1200G" },
    "4.6:HTH2": { location: "Tephra Cave Entrance", gainChoices: "When we had that big fight? // Of course." },
    "4.6:Q5":  { giver: R, location: "South of Ether Light, daytime", objective: "Collect 2 Rabbit Diodes (Colony 9).", rewards: "500G" },
    "4.6:Q6":  { giver: R, location: "North of Ether Light, daytime", objective: "Defeat Verdant Bluchal near Anti-Air Battery 1.", rewards: "1800G" },
    "4.6:UM1": { location: "From the Main Entrance go west, then north to the beach; swerve NE — the larger caterpile is your target.", strategy: "Easy — just lay into him with arts. (First UM kill: trial Hunter-in-Training, plus likely your first gold chest.)" },
    "4.6:Q7":  { giver: R, location: "Tranquil Square heart-to-heart street, daytime", objective: "Collect 1 Giant Hornet (Colony 9).", rewards: "300G" },
    "4.6:Q8":  { giver: R, location: "Tranquil Square HtH street shop, daytime", objective: "Collect 2 Rainbow Zirconia (trade Dionysis, or in the water below Outlook Park).", rewards: "800G" },
    "4.6:Q9":  { giver: R, location: "East of the Gem Man's stall, daytime", objective: "Collect 2 Vang Teeth (Little Vangs at night, west of the Main Entrance).", rewards: "800G" },
    "4.6:Q10": { giver: R, location: "East of the Gem Man's stall, daytime", objective: "Defeat 2 Hand Bunnits (Tephra Hill, the south path from the Main Entrance).", rewards: "800G" },
    "4.6:Q11": { giver: R, location: "East of the Gem Man's stall, daytime", objective: "Defeat 2 Beach Krabbles (southern shore of Anti-Air Battery 1).", rewards: "1000G" },
    "4.6:Q12": { giver: R, location: "East of the Gem Man's stall, daytime", objective: "Defeat 2 Wood Bunnits (Tephra Hill, just past the Hand Bunnits).", rewards: "800G" },
    "4.6:Q13": { giver: R, location: "East of the Gem Man's stall, daytime", objective: "Defeat 3 Light Skeeters (north part of Anti-Air Battery 1).", rewards: "600G" },
    "4.6:Q14": { giver: R, location: "North of Tranquil Square, night", objective: "Collect 1 Yolkless Flamii Egg (Lake Flamii, Anti-Air Battery 1 north shore).", rewards: "1000G" },
    "4.6:Q15": { giver: G, location: "Entrance of Military District, daytime", objective: "Defeat 2 Lake Flamii (Anti-Air Battery 1, north shore).", rewards: "800G" },
    "4.6:Q16": { giver: G, location: "Entrance of Military District, daytime", objective: "Defeat 1 Baby Armu (Anti-Air Battery 1, north shore).", rewards: "1500G" },
    "4.6:Q17": { giver: G, location: "Entrance of Military District, daytime", objective: "Defeat 2 Stone Krabbles (Hazzai Cape — high-level area, use stealth/daytime).", rewards: "800G" },
    "4.6:Q18": { giver: G, location: "Center of the east wall, Military District, daytime", objective: "Defeat Evil Rhanagrot.", rewards: "1800G" },
    "4.6:UM2": { location: "From the Main Entrance up Tephra Hill — behind the boulder on the second knoll.", strategy: "Not difficult — open with Back Slash (he's not looking), then finish with arts." },
    "4.6:Q19": { giver: G, location: "Entrance of Military District, night", objective: "Defeat Lake Magdalena.", rewards: "3000G" },
    "4.6:UM3": { location: "Lake below Outlook Park (jump the cliff west of the landmark).", condition: "Night only", strategy: "Lots of allies — focus him with party commands." },
    "4.6:Q20": { giver: G, location: "North Military District, night", objective: "Defeat 2 Ridge Antols (south coast of Anti-Air Battery 1, night).", rewards: "800G" },
    "4.6:Q21": { giver: G, location: "North Military District, night", objective: "Defeat 1 Cute Brog (south coast of Anti-Air Battery 1, night).", rewards: "500G" },
    "4.6:Q22": { giver: G, location: "North Military District, night", objective: "Defeat 3 Colony Krabbles (Cliff Lake, east shore, night).", rewards: "1200G" },
    "4.6:UM4": { location: "Cliff Lake (the 'f' on the map) — from the colony waters go NW.", strategy: "Break (Shulk) + topple (Reyn), Sharla heals; clear allies one by one." },
    "4.6:UM5": { location: "East shore of Cliff Lake.", condition: "Day only", strategy: "Easy — plow with arts; Reyn topples if it gets chaotic." },
    "4.6:UM6": { location: "Anti-Air Battery 1, far shore (quick-travel Tephra Cave Entrance, jump in, swim SE).", condition: "Dawn only (~05:00)", strategy: "Focus on toppling him; clear the Flamii first." },
    "4.6:Q23": { giver: R, location: "NE of Ether Light, night", objective: "Collect 1 Small Scale (Colony Piranhax, pool below Outlook Park).", rewards: "800G" },
    "4.6:Q24": { giver: R, location: "Weapon Development Lab, daytime", objective: "Collect 2 Small Shells (Beach Krabbles, Anti-Air Battery 1 south shore).", rewards: "500G" },
    "4.6:Q25": { giver: R, location: "Gem Man's Stall — north under the building, up the west stairs, night", objective: "Collect 1 Plate Snow (Colony 9).", rewards: "300G" },
    "4.6:Q26": { giver: R, location: "Central Plaza, by a lamppost, night", objective: "Find the Wedding Ring (behind Dunban's House).", rewards: "1200G, 50 EXP" },
    "4.6:Q27": { giver: R, location: "Tranquil Square HtH street, tree alcove, night", objective: "Find the Spanner (Gem Man's Stall — north overpass, west balcony, up the stairs, alcove to the south).", rewards: "1500G, 50 EXP" },
    "4.6:Q28": { giver: R, location: "South of the Gem Man's Stall, daytime (seated at a table)", objective: "Find the Key (Tranquil Square HtH street — fenced property opposite Dionysus, around the back).", rewards: "1000G, 50 EXP" },
    "4.6:Q29": { giver: R, location: "Wreckage of the mobile artillery, north Residential District, daytime", objective: "Find the Blue Glass Bead (Tranquil Square SW — use the barrels to jump the fence behind the house).", rewards: "1200G, 50 EXP" },
    "4.6:Q30": { giver: R, location: "Balcony north of the Gem Man's Stall, daytime", objective: "Defeat Wallslide Gwynry.", rewards: "2200G" },
    "4.6:UM7": { location: "Tephra Cave — east of the Rear Entrance in Warehouse 2 (at 'Bay' on the map).", strategy: "Keep him toppled: break (Shulk) → topple (Reyn) → Sharla heals. Build gauge via criticals / Shulk's positional bonuses." },
    "4.6:Q31": { giver: G, location: "Escape Pod Bay (east)", objective: "Collect 2 Kneecap Rocks (Tephra Cave).", rewards: "1000G" },
    "4.6:Q32": { giver: G, location: "Escape Pod Bay (east)", objective: "Collect 2 Bright Figs (Tephra Cave).", rewards: "1500G" },
    "4.6:Q33": { giver: G, location: "Escape Pod Bay (east)", objective: "Collect 3 Broken Pincers (Desert Krabble, west shore of Spring of Grief).", rewards: "1200G" },
    "4.6:Q34": { giver: G, location: "Escape Pod Bay (east)", objective: "Collect 1 lot of Brog Smelling Salts (Noble Brog, east shore of Spring of Grief).", rewards: "1500G" },
    "4.6:Q35": { giver: G, location: "Warehouse 2, at the control panels atop the ramp", objective: "Speak with the soldier at the Cylinder Hangar.", rewards: "800G, 50 EXP, Leather Top, Leather Bottom" },
    "4.6:Q36": { giver: G, location: "Cylinder Hangar", objective: "Find the Pendant in Tephra Cave (Vilia Lake, NW), then report at the Cylinder Hangar.", rewards: "950G, 100 EXP, Quark Gear", strategy: "Prerequisite: Missing In Action completed." },
    "4.6:Q37": { giver: G, location: "Warehouse 2", objective: "Collect 3 Arachno Silk (rare drop, Worker Arachno — cave south of Spring of Grief).", rewards: "500G, 100 EXP, Ranger Gloves" },
    "4.6:Q38": { giver: G, location: "Warehouse 2", objective: "Locate the hidden object (from the Leg Pass head west, on the lower ledge).", rewards: "1500G, 100 EXP, Topple Resist II" },
    "4.6:Q39": { giver: G, location: "Escape Pod Bay (east)", objective: "Defeat 2 Devoted Arachno, 4 Resolute Arachno, 3 Zealous Arachno (cave south of Spring of Grief).", rewards: "2500G, 200 EXP, Bleed Defense III" },
    "4.6:Q40": { giver: "Marcia", location: "NW of Ether Light, active 11:00–02:00", objective: "Deliver biscuits to Jiroque (HtH street, night, park on the left), then report to Marcia (daytime).", rewards: "800G, 30 EXP, Swimming Sandals", strategy: "Affinity: registers Marcia & Jiroque; yellow link 'close'." },
    "4.6:Q41": { giver: "Dionysus", location: "Tranquil Square bench (HtH road), 10:00–02:00", objective: "Collect 2 lots of Medicinal Brog Oil (Cute Brogs, Anti-Air Battery 1, night), then report.", rewards: "600G, 50 EXP, Light Shoes" },
    "4.6:Q42": { giver: "Niranira", location: "Top of the stairs by the Tranquil Square HtH, daytime", objective: "Give Niranira's letter to Lukas (nearby), then report back.", rewards: "100G, 50 EXP, Block Guarder", strategy: "Affinity: yellow link 'Kind Friend' (Lukas/Niranira)." },
    "4.6:Q43": { giver: "Desirée", location: "Balcony behind the Gem Man's Stall (NE stairs), night", objective: "Inspect the watch at the Wep. Dev. Lab, collect 3 Blue Chains, repair it, return it to Desirée.", rewards: "750G, 80 EXP, Muscle Up II", strategy: "Prerequisite: Shulk must be party leader." },
    "4.6:Q44": { giver: "Suzana", location: "SW of Tranquil Square, daytime", objective: "Collect 2 lots of Black Nectar (Tephra Cave; easier to trade from Kenny Rohan), then report.", rewards: "500G, 50 EXP, Light Cap", strategy: "Prereq: speak to her son Moritz first. Trading with Kenny may unlock trial 'Friend Number Ten'." },
    "4.6:Q45": { giver: "Emmy Leater", location: "North Military District, daytime", objective: "Find Miller in the Commercial District, then report back.", rewards: "600G, 70 EXP, Dyed Top/Bottoms/Mules" },
    "4.6:Q46": { giver: "Françoise", location: "NW of Tranquil Square, in her flower garden, daytime", objective: "Collect 5 Dawn Hydrangeas (Colony 9), then report.", rewards: "750G, 100 EXP, Soil Gauntlets" },
    "4.6:Q47": { giver: "Lukas", location: "East Tranquil Square", objective: "Rescue Niranira (at Hazzai Cape), then report to Lukas / Moritz / Lukas.", rewards: "800G, 100 EXP, Attack Plus II" },
    "4.6:Q48": { giver: "Giorgio", location: "Ether Light restaurant, daytime", objective: "Collect 5 Dance Apples (Colony 9), then report.", rewards: "1200G, 60 EXP, Caravan Gauntlets" },
    "4.6:Q49": { giver: "Rocco", location: "In front of the Gem Man's Stall, daytime", objective: "Find someone to repair the pendant (Dean, alley south of the Wep. Dev. Lab — Shulk must be in the lead), then report.", rewards: "350G, 100 EXP, Tinted Glasses, Pretty Bangle", strategy: "Prereq: Sonia registered. IMPORTANT — before finishing, speak with Erik (midnight, leaving the Wep. Dev. Lab) to lock the Erik/Dean 'both scientists' link (trial 'constellation'); it's missable if you complete the sequel first." },
    "4.6:Q50": { giver: "Dean", location: "Alley south of the Weapon Development Lab, daytime", objective: "Speak with Sonia → collect 2 Shin Geckos (Tephra Cave; or trade Meifimeifi), then report.", rewards: "1500G, 200 EXP, Lock-On Resist II", strategy: "Prereq: Liliana registered. Shin Geckos are rare — patience or high Colony 9 affinity for the trade. (Trial: the strongest tie.)" },
    "4.6:Q51": { giver: "Suzanna", location: "Tranquil Square", objective: "Collect 2 Heavy Bunniv Iron (Iron Bunniv, south of Mag Mell Ruins, up the ramp), then report.", rewards: "1500G, 300 EXP, Ranger Cap" },
    "4.6:Q52a": { giver: "Monica", location: "Alley north of the Wep. Dev. Lab, 20:00", objective: "Collect a Tephra Drop (Spring of Grief, night), then report to Monica.", rewards: "1200G, 300 EXP, Soil Gear", strategy: "Prereq: Erik registered." },
    "4.6:Q52b": { giver: "Andreas", location: "North/NE of Monica's spot, 22:00", objective: "Collect a Tephra Drop (Spring of Grief, night), then report to Andreas.", rewards: "1200G, 300 EXP, Soil Boots",
      mutexWhy: "Guide picks ANDREAS. Whoever you choose gets a blue link with Monica, so it comes down to how the rejected suitor reacts: Andreas refuses rejection (red link) while Erik accepts it (orange) — so choosing Andreas leaves the stronger affinity chart. (First mutex; trial 'shaping history'.)" },
    "4.6:Q53": { giver: "Leopold", location: "Center of Ether Light, night", objective: "Meet King Squeeze (behind the Gem Man's Stall, night) — triggers a vision and Q54.", rewards: "—", strategy: "Prereq: Sylvaine registered. (Trial: Colony 9 Celeb.)" },
    "4.6:Q54a": { giver: "King Squeeze", location: "Colony 9", objective: "Speak with Sylvaine, collect the Top-Secret Orders (Anti-Air Battery 3 ramp), show King Squeeze.", rewards: "2500G, 500 EXP, Quark Boots" },
    "4.6:Q54b": { giver: "King Squeeze", location: "Colony 9", objective: "Speak with Leopold, collect 5 Caterpile Poison (Eater/Cute Caterpile, Caterpile Nest, Tephra Cave).", rewards: "2500G, 500 EXP, Ranger Shoes",
      mutexWhy: "Guide leans SYLVAINE (investigate route) but calls it a genuine personal choice — it's only +1 stronger. The real question is ethics vs. romance: taking matters into his own hands (Leopold/frame route) damages Leopold's reputation and his relationship with Sylvaine." },
    "4.6:UM8": { location: "Tephra Cave — Caterpile Nest.", strategy: "Easy. Poison-resist armour optional (Sharla covers it). Clear the caterpiles around him first. (Record: Walking Insecticide.)" },
    "4.6:Q55": { giver: "Giorgio", location: "Colony 9", objective: "Two routes: (Giorgio) collect 3 Fresh Armu Milk; or speak to Paola → collect 3 Insanity Mint (Tephra Cave) → report Paola → tell Giorgio.", rewards: "3000G, 300 EXP, HP Up II or Ether Defense Up II", strategy: "Paola's route is better for the affinity chart." },
    "4.6:Q56a": { giver: "Giorgio", location: "Colony 9", objective: "Speak with Paola → defeat Fiendish Bunnit (Cliff Lake, NE) → report Paola, then Giorgio.", rewards: "4500G, 550 EXP, Quark Leggings" },
    "4.6:Q56b": { giver: "Giorgio", location: "Colony 9", objective: "Collect 5 lots of Piranhax Roe (Leg Piranhax) + 3 Juicy Broccoli (Bionis' Leg).", rewards: "5500G, 250 EXP, Quark Gauntlets",
      mutexWhy: "Guide picks PAOLA — speak with her during 'Overworked and Underpaid' to unlock 'Out-Of-Luck Giorgio', which gives a stronger father/daughter link than the alternative 'Pestering Paola'." },
    "4.6:Q57": { giver: "Sesame", location: "East of the Gem Man's stall, behind the boxes, night", objective: "Collect 2 Croaking Brog Bags (Singing Brogs) → deliver to Betty for the Sealed Package → Sesame.", rewards: "1000G, 150 EXP, Critical Up II" },
    "4.6:Q58": { giver: "Sesame", location: "Colony 9 (night)", objective: "Collect 2 Iron Krabble Shells (Colony Krabble, Cliff Lake shore, night) → deliver to Kenny Rohan for the Fragile Package → Sesame.", rewards: "1500G, 200 EXP, Strength Up III", strategy: "Prereq: The Plan: Preparation completed." },
    "4.6:Q59": { giver: "Sesame", location: "Colony 9", objective: "Defeat Dark Murakmor → report, check the lamp post by the Main Entrance → report (triggers a cutscene).", rewards: "5000G, 1200 EXP, Attack Stability II", strategy: "Prereq: all earlier 'The Plan' quests." },
    "4.6:UM9": { location: "Anti-Air Battery 3 summit (from Tranquil Square go NE, jump the fence, swim west, climb the battery).", condition: "Night only", strategy: "Immune to break — just plow through. (Trial: Pro Hunter.)" },
    // Bionis' Leg quests (still §4.6)
    "4.6:Q60": { giver: HT, location: "East of the Raginar Canyon Path", objective: "Defeat 2 Leg Ardun (Gaur Plain).", rewards: "1500G" },
    "4.6:Q61": { giver: HT, location: "East of the Raginar Canyon Path", objective: "Defeat 3 Maker Bunnits (Gaur Plain, north).", rewards: "1200G" },
    "4.6:Q62": { giver: HT, location: "East of the Raginar Canyon Path", objective: "Defeat 5 Field Ponios (Gaur Plain, day).", rewards: "2500G" },
    "4.6:Q63": { giver: HT, location: "East of the Raginar Canyon Path", objective: "Defeat 3 Leg Volff (Gaur Plain, night).", rewards: "1800G" },
    "4.6:Q64": { giver: RF, location: "Up the hill west of the lake, Refugee Camp, day", objective: "Find the Bird Necklace (out the north of camp, east, via Kisk Cave to the plateau beyond).", rewards: "2500G, 200 EXP" },
    "4.6:Q65": { giver: RF, location: "East shore of the Refugee Camp lake, night", objective: "Collect the Torn Paper (Gaur Plain southern peninsula — high-level area, use stealth).", rewards: "2000G, 200 EXP" },
    "4.6:Q66": { giver: RF, location: "Inside the Refugee Camp cave (south of the HtH), night", objective: "Collect 2 Clear Almonds (Tephra Cave).", rewards: "1000G" },
    "4.6:Q67": { giver: RF, location: "Refugee Camp, east shore of the lake, day", objective: "Collect 3 Moth Crawlers (Bionis' Leg).", rewards: "1500G" },
    "4.6:Q68": { giver: RF, location: "On the trail into the Refugee Camp", objective: "Defeat Violent Andante.", rewards: "3800G" },
    "4.6:UM10": { location: "SE of Kamos Guidepost.", strategy: "Nothing new — standard break/topple." },
    "4.6:Q69": { giver: RF, location: "North of the lake at the Refugee Camp, day", objective: "Defeat Vagrant Alfead (Tirkin Headquarters — NW of Kamos Guidepost, in the cavern).", rewards: "4800G" },
    "4.6:UM11": { location: "Tirkin Headquarters (atop the hill).", strategy: "Standard — just don't get surprised." },
    "4.6:Q70": { giver: RF, location: "Refugee Camp, east of the lake by the cliffs, day", objective: "Defeat 2 Basin Antols (forested area leading into the camp).", rewards: "2000G" },
    "4.6:Q71": { giver: RF, location: "West side of the Refugee Camp lake", objective: "Defeat 5 Mechon M64 (Maguel Road — no rush, you pass there later).", rewards: "2500G" },
    "4.6:Q72": { giver: RF, location: "West side of the Refugee Camp lake", objective: "Defeat 2 Brave Tirkins (Tirkin Headquarters).", rewards: "5000G" },
    "4.6:Q73": { giver: RF, location: "Refugee Camp", objective: "Collect 2 Brog Leg Meat (Leg Brog) + 2 Fertile Flamii Egg (Oasis Flamii) — Raguel Lake central island, during a thunderstorm.", rewards: "1000G" },
    "4.6:Q74": { giver: RF, location: "Refugee Camp cavern (Gorman), night", objective: "Collect 2 Tirkin Crests (Javelin Tirkins, Tirkin HQ) + 2 Tirkin Tail Feathers (Archer Tirkins, south of Jacob's Rock).", rewards: "1500G" },
    "4.6:Q75": { giver: RF, location: "Refugee Camp", objective: "Collect 1 Bunnit Sapling (Slugger Bunnit, north of Jacob's Rock Rest Area).", rewards: "1200G" },
    "4.6:Q76": { giver: RF, location: "Refugee Camp (Gorman), night", objective: "Collect 3 Vang Third Molars (Gust Vangs, Kisk Cave).", rewards: "1200G" },
    "4.6:Q77": { giver: "Gorman", location: "Refugee Camp cave interior, night", objective: "Retrieve the stolen Clothes (Tirkin Headquarters) and return them to Gorman.", rewards: "950G, 300 EXP, Grand Armour, Grand Leggings", strategy: "⏱ TIMED — locks at Colony 6 reconstruction (§4.11). Registers Gorman." },
    "4.6:Q78": { giver: "Olga", location: "Refugee Camp cave, daytime", objective: "Collect 5 lots of Glowing Wisp fluid (wisps at night, east of Jacob's Rock through the Gaur Plains — not raining).", rewards: "750G, 300 EXP, Quark Gear", strategy: "⏱ TIMED. Prereq: Gorman registered. Yellow link 'customer' (Gorman/Olga)." },
    "4.6:Q79": { giver: "Matryona", location: "Refugee Camp cavern, daytime", objective: "Speak with Ewan → collect 3 Ponio Neck Meat (Field Ponios, east Gaur Plains, day) → Ewan → Matryona.", rewards: "1200G, 280 EXP, Quark Armour", strategy: "⏱ TIMED. Orange link 'bad feeling' (Ewan/Matryona)." },
    "4.6:Q80": { giver: "Ewan", location: "Refugee Camp cave interior, daytime", objective: "Collect 4 Sour Gooseberries (Bionis' Leg) → Ewan → deliver items to Matryona → Ewan.", rewards: "750G, 200 EXP, Lime Bangle", strategy: "⏱ TIMED. Prereq: A Thoughtful Idea. Link improves to yellow 'interested'." },
    "4.6:Q81": { giver: "Satata", location: "Refugee Camp, south shore of the lake, daytime", objective: "Collect 3 Sticky Web fibers (Leg Arachno, Kisk Cave) → Satata → Kokori → Satata.", rewards: "1000G, 220 EXP, Initial Tension III", strategy: "⏱ TIMED. Prereq: Nikita registered. Blue link 'close family' (Satata/Kokori)." },
    "4.6:Q82": { giver: "Earnest", location: "Shore of the lake outside the Refugee Camp", objective: "Examine the ether mine at Kisk Cave, then report to Earnest.", rewards: "750G, 300 EXP, Lime Bangle" },
    "4.6:Q83": { giver: "Surprise Quest", location: "Gaur Plains, waterfall SE of Jacob's Rock Rest Area", objective: "Defeat 4 Ferocious Volff near the waterfall, then report to the girl.", rewards: "1200G, 300 EXP, Diver Top, Diver Bottoms", strategy: "⏱ TIMED." },
    "4.6:UM12": { location: "Raguel Lake, central island.", condition: "Thunderstorms only", strategy: "—" },
    "4.6:UM13": { location: "NE of 'plain' on the lower map (Gaur Plains).", condition: "Rain or thunderstorm", strategy: "Clear the volff allies first; not a hard fight." },
    "4.6:UM14": { location: "North of the Jacob's Rock Rest Area.", strategy: "—" },
    "4.6:Q84": { giver: RF, location: "Refugee Camp, trail into camp", objective: "Defeat White Eduardo.", rewards: "5500G" },
    "4.6:Q85": { giver: "Satata", location: "South shore of the lake outside the Refugee Camp", objective: "Defeat the Abnormal Brog (Raguel Lake central island), then report to Satata.", rewards: "1100G, 400 EXP, Sleep Resist II", strategy: "⏱ TIMED. Prereq: Being a Good Grandfather." },
    "4.6:Q86": { giver: "Earnest", location: "Bionis' Leg", objective: "Examine the ether deposit at Tranquil Grotto, then report to Earnest.", rewards: "—", strategy: "Prereq: Earnest's Fibs." },
    "4.6:Q87a": { giver: "Matryona", location: "Refugee Camp cave interior, daytime", objective: "Collect 1 Lake Drop (Raguel Lake, east shore north of Tranquil Grotto) → Matryona → give the picture book to Pama.", rewards: "1500G, 250 EXP, Damage Heal II", strategy: "⏱ TIMED. Prereq: A Dash of Colour + A Thoughtful Idea." },
    "4.6:Q87b": { giver: "Arda", location: "Refugee Camp cave interior (rear), daytime", objective: "Collect a Medicinal Herb (from Raguel Bridge: North, SE down the slope under a tree) → Arda.", rewards: "800G, 400 EXP, Arts Heal II",
      mutexWhy: "Guide picks IMAGINATIONS TEMPERED (get the Lake Drop). It gives a clearly better affinity chart; Ewan & Matryona reach green either way, but this route is cleaner. Spirits Raised's only edge is slightly earlier Colony 6 area affinity — negligible since you'll max every area's affinity anyway. ⏱ Both are TIMED." },
    "4.6:HTH3": { location: "Interior of the Refugee Camp cave", gainChoices: "You, by a whisker. // You have dignified qualities." },

    // ---- 4.7: Upper Bionis' Leg & Early Loose Ends ----
    "4.7:UM15": { location: "Tephra Cave — SE of the Mag Mell Ruins, in a small enclave.", strategy: "Easy — a single Back Slash can take him out." },
    "4.7:UM16": { location: "Tephra Cave — Spring of Grief.", condition: "Night only" },
    "4.7:UM17": { location: "Tephra Cave — Vilia Lake." },
    "4.7:Q88": { giver: RF, location: "North of the lake at the Refugee Camp, day", objective: "Defeat Trainer Harmeleon (north of Spiral Valley).", rewards: "4200G" },
    "4.7:UM18": { location: "Bionis' Leg — north of Spiral Valley.", strategy: "Plow with arts; watch the two Berserk Ardun escorting him." },
    "4.7:Q89": { giver: "Earnest", location: "Bionis' Leg", objective: "Place flowers on the grave (NE of Spiral Valley, across the river) and defeat Arrogant Tirkin, then report.", rewards: "1200G, 750 EXP, Grand Boots", strategy: "Prereq: Earnest's Mischief. Speak to Ewan afterward → green 'relief'." },
    "4.7:Q90": { giver: "Gerugu", location: "Traveller's Rest", objective: "Locate Gerugu (from Raguel Bridge: South go NW past the wind ether mine, on the ledge below), then report.", rewards: "750G, 300 EXP, Point Rifle" },
    "4.7:Q91": { giver: "Batubatu", location: "Traveller's Rest", objective: "Find a Tokilos' Egg (east of Zax Guidepost — stealth) and a Pandora Mushroom (Windy Cave below Spiral Valley — sound-stealth).", rewards: "1000G, 450 EXP, Spike II" },
    "4.7:Q92": { giver: "Gerugu", location: "Traveller's Rest", objective: "Locate Batubatu (land bridge to Believer's Paradise) → collect an Ether Rose (Believer's Paradise) → Batubatu.", rewards: "1200G, 750 EXP, Electric Plus III, Grand Gear", strategy: "Affinity → green 'valuable friend' (their best)." },
    "4.7:UM19": { location: "Bionis' Leg — from Bask Cave Passage, the island connected by a ramp; the wisp by Kasharpa Falls (NE) is the target.", condition: "Clear weather, night only", strategy: "Target it so it flies to the cliff by the passage, run up the ramp, and use Lure to engage." },
    "4.7:Q93": { location: "Colony 9 — HtH street, alley on the right then west to Jackson", objective: "Find Jackson a mentor (Kenny Rohan or Giorgio) → Vilia Lake, defeat 5 Tephra Lizards → report.", rewards: "2200G, 450 EXP, Ether Up III", strategy: "Prereq: Dorothy registered (Main Entrance)." },
    "4.7:Q94a": { giver: "Jackson", location: "Colony 9", objective: "Defeat Dim Wisp (Kneecap Hill, night), then report.", rewards: "3800G, 650 EXP, Ether Up II" },
    "4.7:Q94b": { giver: "Jackson", location: "Colony 9", objective: "Collect 5 Raw Piranhax Meat (Colony Piranhax, pool under Outlook Park).", rewards: "3800G, 650 EXP, Pile Driver",
      mutexWhy: "Guide picks JACKSON THE POET (choose Kenny Rohan as mentor): Jackson's link with his teacher is stronger (blue vs green) and Kenny Rohan's link with Giorgio is better (green vs yellow); Dorothy's link is unaffected." },
    "4.7:Q95": { giver: "Kenny Rohan", location: "Colony 9", objective: "Gather info on the mysterious light — speak Suzanna, Françoise, Dionysus → Kenny.", rewards: "2200G, 700 EXP, Auto-Attack Stealth II" },
    "4.7:Q96": { giver: "Kenny Rohan", location: "Colony 9", objective: "Mend the ether lamp, OR throw it away.", rewards: "3400G, 950 EXP, Iron Armor",
      mutexWhy: "Guide picks THROW IT AWAY (use the guardrail south of Central Plaza) — it's done here and now; mending requires farming and a later region for a negligible reward difference." },
    "4.7:Q97": { giver: "Emmy Leater", location: "Colony 9 (Military District entrance, day)", objective: "Defeat 5 Wind Vangs (Spring of Grief), then report.", rewards: "1100G, 180 EXP, Ether Defense Up III", strategy: "Prereq: Raoul registered." },
    "4.7:Q98": { giver: "Emmy Leater", location: "Colony 9", objective: "Defeat Lurker Krabble (Vilia Lake) or Lurker Brog (Spring of Grief), then report.", rewards: "1800G, 250 EXP, Flame Gear", strategy: "Either target is fine — same reward & affinity. (Trial: generous friend.)" },

    // ---- 4.8: Colony 6 first visit ----
    "4.8:Q99": { giver: "Daza", location: "Watchpoint Junction", objective: "Find the Nopon Coin (down the elevator to Splintered Path; at the second fork go SE then south), then report.", rewards: "850G, 320 EXP, Break II", strategy: "Registers Daza." },
    "4.8:Q100": { giver: "Daza", location: "Watchpoint Junction", objective: "Defeat 4 Yellow Antols (Splintered Path), 6 Soft Hoxes (Watchpoint Junction), 3 Water Upa (rainstorm at the Drainage Outlet).", rewards: "900G, 400 EXP, Pelt Top, Pelt Bottoms" },
    "4.8:UM20": { location: "NE of the Drainage Outlet.", condition: "Rain or thunderstorm only" },
    "4.8:Q101": { giver: "Daza", location: "Watchpoint Junction", objective: "Deliver Daza's letter to Gerugu → take Gerugu's response back to Daza.", rewards: "1000G, 500 EXP, Slow III, Top Secret Data", strategy: "Affinity → green 'companions' (Gerugu/Daza)." },

    // ---- 4.9: Ether Mine ----
    "4.9:UM21": { location: "Glowmoss Lake.", strategy: "Mostly ether attacks — keep him toppled (he's susceptible to break)." },
    "4.9:UM22": { location: "Stairs near Test Pit 4." },
    "4.9:UM23": { location: "Fire Ether Deposits near Test Pit 4.", strategy: "Likely unlocks the records Fire It Up and Unbreakable Bond." },
    "4.9:HTH4": { location: "Bionis' Leg (needs blue Shulk/Sharla affinity and Juju seen to safety)", gainChoices: "I wish I had it. // You can save someone's life!" },

    // ---- 4.10: Satorl Marsh ----
    "4.10:Q101b": { giver: "Cheryl", location: "Balcony north of the Gem Man's Stall, Colony 9, day", objective: "Collect 3 uniform pieces — Tatty Armor (Spring of Grief, Tephra Cave), Twisted Gun (north of the Observation Platform, Bionis' Leg), Nicked Knife (by the Shining Pond, Satorl Marsh) — then report.", rewards: "4500G, 1500 EXP, Bomber Lancer", strategy: "After completion, speak Marcia (blue 'friends always'), Cheryl (green 'old friends'), Jan (green 'old suitor')." },
    "4.10:Q102": { giver: "Nopon Merchant", location: "Nopon Merchant Camp", objective: "Defeat 2 Detox Brogs (Crown Tree).", rewards: "5800G" },
    "4.10:Q103": { giver: "Nopon Merchant", location: "Nopon Merchant Camp", objective: "Defeat 3 Coppice Quadwings (Lacus Swamp, day).", rewards: "5200G" },
    "4.10:Q104": { giver: "Nopon Merchant", location: "Nopon Merchant Camp", objective: "Defeat 2 Mist Rhouguls (Barren Moor, day).", rewards: "6800G" },
    "4.10:Q105": { giver: "Nopon Merchant", location: "Nopon Merchant Camp", objective: "Defeat 1 Officer Volff (NW of Barren Moor, day).", rewards: "6500G" },
    "4.10:Q106": { giver: "Bokoko", location: "Nopon Merchant Camp", objective: "Find and save Kacha (Exile Fortress interior).", rewards: "3500G, 410 EXP, Jungle Cap/Gloves/Shoes", strategy: "Green link 'like family' (Kacha/Bokoko)." },
    "4.10:UM25": { location: "Zaldandia Falls.", condition: "Day + clear weather only" },
    "4.10:UM26": { location: "Plateau above Poison Swamp.", strategy: "Has Igna allies — clear them one by one first; he's far easier alone." },
    "4.10:UM27": { location: "Plateau SE of the Silent Obelisk." },
    "4.10:Q107": { giver: "Zazadan", location: "Nopon Refuge", objective: "Collect 5 Lemon Stones + 2 Twin Flamii Eggs (Lacus Swamp).", rewards: "2400G, 400 EXP, Mist Gel/Cream/Sandals", strategy: "Registers Zazadan." },
    "4.10:Q108": { giver: "Zazadan", location: "Nopon Refuge", objective: "Defeat 8 Ogre Bunnia (Glowing Obelisk).", rewards: "3200G, 680 EXP, Swep Gear, Agility Up II" },
    "4.10:Q109": { giver: "Zazadan", location: "Nopon Refuge", objective: "Defeat Sunlight Sachik.", rewards: "4500G, 850 EXP, Swep Gauntlets, HP II" },
    "4.10:UM29": { location: "Silent Obelisk.", condition: "Day + clear weather only", strategy: "Immune to break (no topple) — reserve the party gauge for revives. Level Shield to 2 to block his talent art; Shulk leads, Sharla heals." },
    "4.10:Q110": { giver: "Zazadan", location: "Nopon Refuge", objective: "Collect a Nopon Potion (cavern south of the Nopon Merchant Camp).", rewards: "5100G, 1000 EXP, Swep Boots, Ether Up II" },
    "4.10:Q111": { giver: "Zazadan", location: "Nopon Refuge", objective: "Investigate the Shining Pond (dip the Red Pollen Orb to get Highmore Caviar).", rewards: "5800G, 1500 EXP, Pioneer" },
    "4.10:Q112": { giver: "Zazadan", location: "Nopon Refuge", objective: "Deliver the Highmore Caviar to Dedeba (he's in Frontier Village — reachable at §4.14).", rewards: "7800G, 2500 EXP, Panther Bottoms" },
    "4.10:Q113": { giver: "Bokoko", location: "Nopon Merchant Camp", objective: "Collect 4 Feather Leaves, 3 Wool Rocks, 3 Fancy Volff Hides, 4 Glowing Upa Seeds.", rewards: "10500G, 1000 EXP, Iron Armour, Nopon Boots" },
    "4.10:Q114": { giver: "Kacha", location: "Nopon Merchant Camp", objective: "Defeat 5 Deluded Igna, dig up the Giant's Key, then use the Wall of Sin → Exile Fortress roof altar → report.", rewards: "5900G, 2200 EXP, Recovery Up IV" },
    "4.10:Q115": { giver: "Kacha", location: "Nopon Merchant Camp", objective: "Collect the Giant's Mirror (Daksha Shrine) → offer it at the Exile Fortress roof altar → run → report.", rewards: "9100G, 3100 EXP, Double Attack IV, Daring Of The Giants" },
    "4.10:HTH7": { location: "Mining Base (Ether Mine)", gainChoices: "It's a beautiful watch. // I can fix it!" },
    "4.10:HTH8": { location: "Zaldandia Waterfall", condition: "Night only", gainChoices: "Really? Interesting. // Will it ever run out?" },
    "4.10:Q116": { location: "Sororal Statues", objective: "Prepare for the ceremony (collect the Offerings), then use the Adulthood Emblem → defeat the Lv. 28 Satorl Guardian.", strategy: "Story quest." },
    "4.10:Q117": { location: "Sororal Statues", objective: "Collect the Radiant Offerings — White (Basin Cave), Rainbow (Altar of Fate), Dull (Dark Swamp island), Blue (SW Igna Territory).", strategy: "Story quest." },
    "4.10:UM30": { location: "Altar of Fate base, SE." },
    "4.10:UM31": { location: "SW Igna Territory.", strategy: "Guards the Blue Radiant for the ceremony." },
    "4.10:UM32": { location: "Daksha Shrine (Bionis' Leg)." }
  }
};
